language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-roboptim
  - brew tap --repair
env:
  - PACKAGE=roboptim-core
  - PACKAGE=roboptim-core-plugin-eigen
  - PACKAGE=roboptim-core-plugin-ipopt
  - PACKAGE=roboptim-core-plugin-cminpack
script:
  - export KNITRO_USERNAME="dummy"
  - export KNITRO_PASSWORD="dummy"
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - brew test $PACKAGE
notifications:
  email: false
